language: node_js
node-js: 
  - "7"
before_script:
  - nvm install 7
  - npm install -g gulp
script: npm run build
after_success:
  - eval "$(ssh-agent -s -A)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - sh deploy.sh
