language: node_js
node-js:
- '7'
before_script:
- nvm install 7
- npm install -g gulp
script: npm run build
after_success:
- sh .travis/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_d3e064728e0d_key -iv $encrypted_d3e064728e0d_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
